-- MySQL Script generated by MySQL Workbench
-- Mon May  4 14:51:01 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Kaizen_Classroom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Kaizen_Classroom` ;

-- -----------------------------------------------------
-- Schema Kaizen_Classroom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kaizen_Classroom` DEFAULT CHARACTER SET utf8 ;
USE `Kaizen_Classroom` ;

-- -----------------------------------------------------
-- Table `Kaizen_Classroom`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kaizen_Classroom`.`Users` ;

CREATE TABLE IF NOT EXISTS `Kaizen_Classroom`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kaizen_Classroom`.`Parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kaizen_Classroom`.`Parents` ;

CREATE TABLE IF NOT EXISTS `Kaizen_Classroom`.`Parents` (
  `idParents` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(30) NOT NULL,
  `phone_number` VARCHAR(13) NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`idParents`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kaizen_Classroom`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kaizen_Classroom`.`Students` ;

CREATE TABLE IF NOT EXISTS `Kaizen_Classroom`.`Students` (
  `idStudents` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(30) NOT NULL,
  `birthdate` DATE NOT NULL,
  `is_active` TINYINT NOT NULL,
  `Parents_idParents` INT NOT NULL,
  PRIMARY KEY (`idStudents`),
  INDEX `fk_Students_Parents1_idx` (`Parents_idParents` ASC) VISIBLE,
  UNIQUE INDEX `Student_Unique` (`lastname` ASC, `firstname` ASC, `birthdate` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Parents1`
    FOREIGN KEY (`Parents_idParents`)
    REFERENCES `Kaizen_Classroom`.`Parents` (`idParents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kaizen_Classroom`.`Follow-ups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kaizen_Classroom`.`Follow-ups` ;

CREATE TABLE IF NOT EXISTS `Kaizen_Classroom`.`Follow-ups` (
  `idFollow-ups` INT NOT NULL AUTO_INCREMENT,
  `tracking_number` INT NOT NULL,
  `session_date` DATE NOT NULL,
  `is_present` TINYINT NOT NULL,
  `reason_absence` VARCHAR(100) NULL,
  `educational_content` VARCHAR(500) NULL,
  `observations` VARCHAR(150) NULL,
  `start_hour` TIME NOT NULL,
  `end_hour` TIME NOT NULL,
  `Students_idStudents` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idFollow-ups`),
  INDEX `fk_Follow-ups_Students1_idx` (`Students_idStudents` ASC) VISIBLE,
  INDEX `fk_Follow-ups_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  UNIQUE INDEX `tracking_number_UNIQUE` (`tracking_number` ASC) VISIBLE,
  CONSTRAINT `fk_Follow-ups_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `Kaizen_Classroom`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Follow-ups_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `Kaizen_Classroom`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kaizen_Classroom`.`Assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kaizen_Classroom`.`Assignments` ;

CREATE TABLE IF NOT EXISTS `Kaizen_Classroom`.`Assignments` (
  `idAssignments` INT NOT NULL,
  `Students_idStudents` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idAssignments`),
  INDEX `fk_Students_has_Users_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_Students_has_Users_Students1_idx` (`Students_idStudents` ASC) VISIBLE,
  CONSTRAINT `fk_Students_has_Users_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `Kaizen_Classroom`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Users_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `Kaizen_Classroom`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
